### ISSUE TITLE
"NOT???" replay bug

### ISSUE THREAD

**Issue by KotomanOrNot** [TobyAdd/GDH#138]
I record my replay it has size, if i set play and restart the level it works but if i want to save it it says "NOT???"

**Comment by TobyAdd** [comment]
In this scenario, if both the replay and name aren't empty but the file fails to open for writing, it could be due to a path not found error. The directory "GDH/macros/" might not exist, or there could be permission issues for GDH to create files in that directory. To resolve this, check if the directory exists.

**Comment by KotomanOrNot** [comment]
Thank you for explaining but it kinda disappeared after an hour or so

**Comment by TobyAdd** [comment]
Do not specify forbidden characters or macro name. Read more: https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names
