### ISSUE TITLE
There is a trojan???

### ISSUE THREAD

**Issue by NNession** [TobyAdd/GDH#152]
Windows defender deletes GDH.dll because its a trojan
here's what it says:
Trojan:Wln32/Znyonm
![image](https://github.com/TobyAdd/GDH/assets/121925782/1e1fa99d-d1bf-4196-9d15-0a31ac4e8b0b)
when i try downloading release.zip again, it gives the same thing
because of this error i can't play gd anymore
![image](https://github.com/TobyAdd/GDH/assets/121925782/ea70bb9c-a55e-44e8-8552-6d31cdb45829)

**Comment by IzzikRider** [comment]
trojan in this mod menu only you!

**Comment by TobyAdd** [comment]
Because you're asking the wrong question. That's precisely why it detects a virus. When you ask the creator of the antivirus this question, then it will stop detecting the virus. Why? Very simple - because there's currently no accountability for false positives, so antiviruses can freely report any information. But if you rely on antiviruses and trust them, then trusting GDH isn't necessary, it's easier not to use them at all.

**Comment by NNession** [comment]
> Because you're asking the wrong question. That's precisely why it detects a virus. When you ask the creator of the antivirus this question, then it will stop detecting the virus. Why? Very simple - because there's currently no accountability for false positives, so antiviruses can freely report any information. But if you rely on antiviruses and trust them, then trusting GDH isn't necessary, it's easier not to use them at all.

oh sorry
I didn't know because i don't usually use mods for any game
sorry to bother you
