### ISSUE TITLE
virus

### ISSUE THREAD

**Issue by dogsarebetter1** [TobyAdd/GDH#158]
windows defender says its a virus

**Comment by TobyAdd** [comment]
You're asking the wrong question. That's precisely why it detects a virus. When you ask the creator of the antivirus this question, then it will stop detecting the virus. Why? Very simple - because there's currently no accountability for false positives, so antiviruses can freely report any information. But if you rely on antiviruses and trust them, then trusting GDH isn't necessary, it's easier not to use them at all.
