### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by Jiraiya15co** [TobyAdd/GDH#79]
My anti virus (norton 360) flagged the .dll file GDH.dll (i dont have a cracked version of norton)

![Screenshot 2024-01-07 125042](https://github.com/TobyAdd/GDH/assets/155888133/63a8b2a7-090c-42be-9e80-e4e4d939ea62)

**Comment by Lukemfor** [comment]
Instead of opening a game it opened a cmd. I think it's a glitch or stealer

**Comment by geomydas** [comment]
False positive. This application is open-source which means you can see it's code.
If you don't know what open source means, I'll use an analogy
Imagine, you know a company. If it is closed-source, you will only get your product but if it is open-source, you will know how the company operates, who are hired and every info of it

**Comment by TobyAdd** [comment]
You are just stupid people who don't understand what open source is. The console is enabled because I forgot to turn it off, when I made Noclip Accuracy and other hacks, I needed some way to display information to see if it works correctly. The game is crashing because GDH is not yet adapted to Geometry Dash 2.202. You are just senseless people who without proof say that there stealer and creating useless issues. Fake and stop spreading bullshit.
